---
all:
  vars:
    greenbone_install_mode: docker
    greenbone_docker_use_official_repo: true
    greenbone_web_bind_address: "127.0.0.1"
  children:
    greenbone_masters:
      hosts:
        greenbone-rocky-standalone:
          ansible_host: 192.0.2.10
          ansible_user: rocky
    greenbone_workers:
      hosts: {}
