---
greenbone_supported_distributions_normalized:
  - ubuntu
  - debian
  - kali
  - kalignulinux
  - redhat
  - redhatenterpriselinux
  - almalinux
  - rocky
  - rockylinux
  - oraclelinux
  - oraclelinuxserver
  - alpine

greenbone_install_mode: auto
greenbone_auto_native_distributions_normalized:
  - kali
  - kalignulinux

greenbone_rocky_docker_supported_major_versions:
  - 9
  - 10

greenbone_rocky_docker_supported_architectures:
  - x86_64
  - aarch64

greenbone_rocky10_min_ansible_core_version: "2.19.0"
greenbone_rocky10_x86_64_v3_required_cpu_flag_groups:
  - - cx16
  - - lahf_lm
  - - popcnt
  - - pni
    - sse3
  - - ssse3
  - - sse4_1
  - - sse4_2
  - - avx
  - - avx2
  - - bmi1
  - - bmi2
  - - f16c
  - - fma
  - - abm
    - lzcnt
  - - movbe
  - - xsave
greenbone_rocky_validate_service_retries: 60
greenbone_rocky_validate_service_delay: 15

greenbone_work_dir: /opt/greenbone-community
greenbone_admin_user: admin
greenbone_controller_secret_dir: "{{ (lookup('env', 'PWD') | default('.', true)) + '/.secrets' }}"
greenbone_admin_password: ""
greenbone_web_bind_address: "127.0.0.1"
greenbone_web_https_port: 443
greenbone_web_gsad_port: 9392

greenbone_worker_ospd_port: 9390
