---
extends: default

ignore: |
  .venv/
  greenbone-community-ansible/

rules:
  line-length:
    max: 160
    level: warning
  truthy:
    allowed-values: ['true', 'false']
  comments-indentation: disable
