$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")

function Read-RepoFile {
    param([string] $RelativePath)
    Get-Content -Raw -Path (Join-Path $RepoRoot $RelativePath)
}

function Assert-Contains {
    param(
        [string] $Text,
        [string] $Needle,
        [string] $Context
    )

    if (-not $Text.Contains($Needle)) {
        throw "Missing expected content in ${Context}: ${Needle}"
    }
}

function Assert-NotContains {
    param(
        [string] $Text,
        [string] $Needle,
        [string] $Context
    )

    if ($Text.Contains($Needle)) {
        throw "Unexpected content in ${Context}: ${Needle}"
    }
}

$commonDefaults = Read-RepoFile "roles/greenbone_common/defaults/main.yml"
$commonTasks = Read-RepoFile "roles/greenbone_common/tasks/main.yml"
$dockerDefaults = Read-RepoFile "roles/greenbone_docker/defaults/main.yml"
$redhatTasks = Read-RepoFile "roles/greenbone_docker/tasks/redhat.yml"
$groupVars = Read-RepoFile "group_vars/all.yml"
$masterPreflightTasks = Read-RepoFile "roles/greenbone_master/tasks/preflight.yml"
$masterDockerTasks = Read-RepoFile "roles/greenbone_master/tasks/docker.yml"
$rockyInventory = Read-RepoFile "inventories/rocky-standalone/hosts.yml"
$sitePlaybook = Read-RepoFile "site.yml"
$installPlaybook = Read-RepoFile "playbooks/install.yml"
$rockyBootstrapPlaybook = Read-RepoFile "playbooks/bootstrap-rocky-standalone.yml"
$rockyDockerRepoSmoke = Read-RepoFile "scripts/dev/Test-RockyDockerRepo.sh"
$rockyDockerRepoSmokePs = Read-RepoFile "scripts/dev/Test-RockyDockerRepo.ps1"
$rockyDockerRepoMetadata = Read-RepoFile "scripts/dev/Test-RockyDockerRepoMetadata.py"
$rockyAcceptanceEvidence = Read-RepoFile "scripts/dev/Test-RockyAcceptanceEvidence.py"
$rockyAcceptanceInventoryRenderer = Read-RepoFile "scripts/dev/Render-RockyAcceptanceInventory.py"
$rockyLocalAcceptanceRunner = Read-RepoFile "scripts/dev/Run-RockyStandaloneAcceptance.sh"
$rockyLocalAcceptanceRunnerPs = Read-RepoFile "scripts/dev/Run-RockyStandaloneAcceptance.ps1"
$rockyAcceptanceWorkflowShell = Read-RepoFile "scripts/dev/Test-RockyAcceptanceWorkflowShell.py"
$rockyAcceptanceReadiness = Read-RepoFile "scripts/dev/Test-RockyAcceptanceReadiness.py"
$greenboneContainerPlatforms = Read-RepoFile "scripts/dev/Test-GreenboneContainerPlatforms.py"
$rockyPreflightPlaybook = Read-RepoFile "playbooks/preflight-rocky-standalone.yml"
$rockyValidationPlaybook = Read-RepoFile "playbooks/validate-rocky-standalone.yml"
$rockyDiagnosticsPlaybook = Read-RepoFile "playbooks/collect-rocky-standalone-diagnostics.yml"
$supportMatrix = Read-RepoFile "docs/support-matrix.md"
$rockyRunbook = Read-RepoFile "docs/rocky-standalone.md"
$variablesDoc = Read-RepoFile "docs/variables.md"
$troubleshootingDoc = Read-RepoFile "docs/troubleshooting.md"
$readme = Read-RepoFile "README.md"
$readmeEn = Read-RepoFile "docs/README.en.md"
$readmeAr = Read-RepoFile "docs/README.ar.md"
$readmeEs = Read-RepoFile "docs/README.es.md"
$readmeHi = Read-RepoFile "docs/README.hi.md"
$readmeZh = Read-RepoFile "docs/README.zh.md"
$yamllint = Read-RepoFile ".yamllint.yml"
$makefile = Read-RepoFile "Makefile"
$workflow = Read-RepoFile ".github/workflows/ansible-lint.yml"
$acceptanceWorkflow = Read-RepoFile ".github/workflows/rocky-standalone-acceptance.yml"

Assert-Contains $commonDefaults "greenbone_rocky_docker_supported_major_versions:" "common defaults"
Assert-Contains $commonDefaults "  - 9" "common defaults"
Assert-Contains $commonDefaults "  - 10" "common defaults"
Assert-Contains $commonDefaults "greenbone_rocky_docker_supported_architectures:" "common defaults"
Assert-Contains $commonDefaults "  - x86_64" "common defaults"
Assert-Contains $commonDefaults "  - aarch64" "common defaults"
Assert-Contains $commonDefaults "greenbone_rocky10_x86_64_v3_required_cpu_flag_groups:" "common defaults"
Assert-Contains $commonDefaults "  - - avx2" "common defaults"
Assert-Contains $commonDefaults "    - lzcnt" "common defaults"
Assert-Contains $commonDefaults "  - rockylinux" "common defaults"
Assert-Contains $commonDefaults "default('.', true)" "common defaults"
Assert-Contains $groupVars "default('.', true)" "group vars"
Assert-Contains $groupVars "Rocky Linux 9/10 standalone installs must set docker explicitly" "group vars"
Assert-Contains $groupVars 'greenbone_admin_password: ""' "group vars"
Assert-Contains $commonTasks "Assert Rocky Linux Docker standalone support" "common tasks"
Assert-Contains $commonTasks "greenbone_install_mode == 'docker'" "common tasks"
Assert-Contains $commonTasks "greenbone_effective_install_mode == 'docker'" "common tasks"
Assert-Contains $commonTasks "greenbone_distribution_normalized in ['rocky', 'rockylinux']" "common tasks"
Assert-Contains $commonTasks "ansible_distribution_major_version | int in greenbone_rocky_docker_supported_major_versions" "common tasks"
Assert-Contains $commonTasks "ansible_architecture in greenbone_rocky_docker_supported_architectures" "common tasks"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_supported_major_versions" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "ansible_distribution_major_version | int in greenbone_preflight_supported_major_versions" "Rocky preflight playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_supported_major_versions" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "ansible_distribution_major_version | int in greenbone_validate_supported_major_versions" "Rocky validation playbook"
Assert-Contains $commonTasks "greenbone_docker_use_official_repo | default(true) | bool" "common tasks"
Assert-Contains $commonTasks "Bootstrap DNF5 Python bindings when target reports DNF5" "common tasks"
Assert-Contains $commonTasks "ansible.builtin.raw" "common tasks"
Assert-Contains $commonTasks "set -eu" "common tasks"
Assert-Contains $commonTasks "dnf -q list --available python3-libdnf5" "common tasks"
Assert-Contains $commonTasks "greenbone_common_rocky10_dnf5_bootstrap" "common tasks"
Assert-Contains $commonTasks "Check whether curl-minimal is installed on RedHat family" "common tasks"
Assert-Contains $commonTasks "greenbone_common_curl_minimal_result" "common tasks"
Assert-Contains $commonTasks "'curl-minimal' if greenbone_common_curl_minimal_result.rc | default(1) == 0 else 'curl'" "common tasks"
Assert-Contains $dockerDefaults "  - podman" "docker defaults"
Assert-Contains $redhatTasks "greenbone_docker_rpm_repo_family" "redhat docker tasks"
Assert-Contains $redhatTasks "else 'centos'" "redhat docker tasks"
Assert-Contains $redhatTasks "https://download.docker.com/linux/{{ greenbone_docker_rpm_repo_family }}/docker-ce.repo" "redhat docker tasks"
Assert-Contains $redhatTasks "greenbone_docker_rpm_gpg_key_url" "redhat docker tasks"
Assert-Contains $redhatTasks "Import Docker RPM GPG key" "redhat docker tasks"
Assert-Contains $redhatTasks "ansible.builtin.rpm_key" "redhat docker tasks"
Assert-Contains $masterPreflightTasks "Set generated Greenbone admin password file path" "master preflight tasks"
Assert-Contains $masterPreflightTasks "default('.', true)" "master preflight tasks"
Assert-Contains $masterPreflightTasks "length=32" "master preflight tasks"
Assert-Contains $masterPreflightTasks "throttle: 1" "master preflight tasks"
Assert-Contains $masterDockerTasks "Assert Greenbone Docker compose web port mappings are patched" "master Docker tasks"
Assert-Contains $masterDockerTasks "Validate Greenbone Docker compose configuration" "master Docker tasks"
Assert-Contains $rockyInventory "greenbone_install_mode: docker" "rocky standalone inventory"
Assert-Contains $rockyInventory "greenbone_docker_use_official_repo: true" "rocky standalone inventory"
Assert-Contains $rockyInventory "ansible_user: rocky" "rocky standalone inventory"
Assert-Contains $sitePlaybook "ansible.builtin.import_playbook: playbooks/install.yml" "site playbook"
Assert-Contains $installPlaybook "import_playbook: bootstrap-rocky-standalone.yml" "install playbook"
Assert-Contains $rockyPreflightPlaybook "import_playbook: bootstrap-rocky-standalone.yml" "Rocky preflight playbook"
Assert-Contains $rockyBootstrapPlaybook "Bootstrap Rocky Linux standalone Python support" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "gather_facts: false" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "ansible.builtin.raw" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook 'rocky_major="${VERSION_ID:-}"' "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "python3-dnf" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "python3-libdnf" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "python3-libdnf5" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "dnf -q list --available python3-libdnf5" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "dnf -y install" "Rocky bootstrap playbook"
Assert-Contains $rockyBootstrapPlaybook "greenbone_rocky_python_bootstrap=changed" "Rocky bootstrap playbook"
Assert-Contains $supportMatrix "| Rocky Linux | 9.x | x86_64, aarch64 | Docker standalone master | Docker CentOS RPM repo | Supported by this project |" "support matrix"
Assert-Contains $supportMatrix "| Rocky Linux | 10.x | x86_64, aarch64 | Docker standalone master | Docker CentOS RPM repo | Supported by this project |" "support matrix"
Assert-Contains $supportMatrix "Rocky's x86-64-v3 baseline" "support matrix"
Assert-Contains $supportMatrix "x86-64-v2 hardware is outside this support target" "support matrix"
Assert-Contains $supportMatrix "Rocky 10 x86_64 x86-64-v3 CPU flags" "support matrix"
Assert-Contains $supportMatrix "x86-64-v3 CPU flag proof" "support matrix"
Assert-Contains $supportMatrix "Test-RockyAcceptanceEvidence.py --summary-json" "support matrix"
Assert-Contains $supportMatrix "greenbone_docker_use_official_repo: true" "support matrix"
Assert-Contains $supportMatrix "The CI smoke check does not start the full Greenbone stack" "support matrix"
Assert-Contains $supportMatrix "scripts/dev/Test-RockyDockerRepo.ps1" "support matrix"
Assert-Contains $supportMatrix "quay.io/rockylinux/rockylinux:9" "support matrix"
Assert-Contains $supportMatrix "quay.io/rockylinux/rockylinux:10" "support matrix"
Assert-Contains $supportMatrix "validates Rocky BaseOS/AppStream prerequisite package publication" "support matrix"
Assert-Contains $supportMatrix '`python3-dnf` and `python3-libdnf`' "support matrix"
Assert-Contains $supportMatrix "Docker's CentOS RPM GPG key" "support matrix"
Assert-Contains $supportMatrix "publication for x86_64 and aarch64" "support matrix"
Assert-Contains $supportMatrix "publish both linux/amd64 and linux/arm64 manifests" "support matrix"
Assert-Contains $supportMatrix "Rocky smoke-test container images" "support matrix"
Assert-Contains $supportMatrix "core services and" "support matrix"
Assert-Contains $supportMatrix "localhost web mappings used by Rocky validation" "support matrix"
Assert-Contains $supportMatrix "real Rocky 9 and Rocky 10 hosts" "support matrix"
Assert-Contains $supportMatrix ".github/workflows/rocky-standalone-acceptance.yml" "support matrix"
Assert-Contains $supportMatrix "ROCKY_BECOME_PASSWORD" "support matrix"
Assert-Contains $supportMatrix "verifies SSH and sudo access with an" "support matrix"
Assert-Contains $supportMatrix "before target Python is required" "support matrix"
Assert-Contains $supportMatrix "rejects hosts where" "support matrix"
Assert-Contains $supportMatrix "/opt/greenbone-community" "support matrix"
Assert-Contains $supportMatrix "known Greenbone containers already exist" "support matrix"
Assert-Contains $supportMatrix "validates that the artifact contains one complete Rocky 9 report" "support matrix"
Assert-Contains $supportMatrix "validated_at" "support matrix"
Assert-Contains $supportMatrix "last" "support matrix"
Assert-Contains $supportMatrix "24 hours" "support matrix"
Assert-Contains $supportMatrix "GitHub workflow run ID" "support matrix"
Assert-Contains $supportMatrix "attempt values" "support matrix"
Assert-Contains $supportMatrix "Self-hosted" "support matrix"
Assert-Contains $supportMatrix "v2.327.1 or later" "support matrix"
Assert-Contains $supportMatrix "playbooks/bootstrap-rocky-standalone.yml" "support matrix"
Assert-Contains $supportMatrix "fact gathering" "support matrix"
Assert-Contains $supportMatrix 'uses `raw` commands' "support matrix"
Assert-Contains $supportMatrix "playbooks/preflight-rocky-standalone.yml" "support matrix"
Assert-Contains $supportMatrix "target-host" "support matrix"
Assert-Contains $supportMatrix "network access" "support matrix"
Assert-Contains $supportMatrix "target Rocky major version and architecture" "support matrix"
Assert-Contains $supportMatrix '`ansible-core` 2.19.0 or newer' "support matrix"
Assert-Contains $supportMatrix 'values of `dnf` or `dnf5`' "support matrix"
Assert-Contains $supportMatrix 'requires the target-side `python3-libdnf5` binding' "support matrix"
Assert-Contains $supportMatrix "minimum CPU/RAM/disk resources" "support matrix"
Assert-Contains $supportMatrix "required Docker RPM packages" "support matrix"
Assert-Contains $supportMatrix 'including `openvas`, `openvasd`, and' "support matrix"
Assert-Contains $supportMatrix "validation timestamp" "support matrix"
Assert-Contains $supportMatrix "OS family, kernel, package" "support matrix"
Assert-Contains $supportMatrix "conditional DNF5 backend runtime status" "support matrix"
Assert-Contains $supportMatrix 'controller `ansible-core`' "support matrix"
Assert-Contains $supportMatrix "memory, and free-disk facts" "support matrix"
Assert-Contains $supportMatrix "install mode" "support matrix"
Assert-Contains $supportMatrix "official Docker repo" "support matrix"
Assert-Contains $supportMatrix "Docker's RPM GPG key" "support matrix"
Assert-Contains $supportMatrix "localhost web bind address" "support matrix"
Assert-Contains $supportMatrix "127.0.0.1:443" "support matrix"
Assert-Contains $supportMatrix "127.0.0.1:443:443" "support matrix"
Assert-Contains $supportMatrix "127.0.0.1:9392:9392" "support matrix"
Assert-Contains $supportMatrix "waits for required core compose services" "support matrix"
Assert-Contains $supportMatrix "local HTTPS" "support matrix"
Assert-Contains $supportMatrix "GSAD endpoints" "support matrix"
Assert-Contains $supportMatrix "generated admin password file exists" "support matrix"
Assert-Contains $supportMatrix "non-empty" "support matrix"
Assert-Contains $supportMatrix "is mode" "support matrix"
Assert-Contains $supportMatrix '`0600`' "support matrix"
Assert-Contains $supportMatrix "compose service" "support matrix"
Assert-Contains $supportMatrix "service readiness gate passes" "support matrix"
Assert-Contains $supportMatrix "900-second service startup window" "support matrix"
Assert-Contains $supportMatrix "one complete Rocky 9 report" "support matrix"
Assert-Contains $supportMatrix "complete Rocky 10 report" "support matrix"
Assert-Contains $supportMatrix "playbooks/collect-rocky-standalone-diagnostics.yml" "support matrix"
Assert-Contains $supportMatrix "rocky-standalone-diagnostics" "support matrix"
Assert-Contains $supportMatrix "Docker info, SELinux, firewalld, repo trust" "support matrix"
Assert-Contains $supportMatrix "recent Compose log diagnostics" "support matrix"
Assert-Contains $supportMatrix "does not include" "support matrix"
Assert-Contains $supportMatrix "generated admin password" "support matrix"
Assert-Contains $supportMatrix "Test-RockyAcceptanceReadiness.py" "support matrix"
Assert-Contains $supportMatrix 'authenticated `gh`' "support matrix"
Assert-Contains $supportMatrix "required repository secret names are present" "support matrix"
Assert-Contains $supportMatrix "Run-RockyStandaloneAcceptance.sh" "support matrix"
Assert-Contains $supportMatrix "same live preflight, install, validation, evidence freshness check" "support matrix"
Assert-Contains $supportMatrix "Run-RockyStandaloneAcceptance.ps1" "support matrix"
Assert-Contains $supportMatrix "WSLENV" "support matrix"
Assert-Contains $supportMatrix "https://docs.docker.com/engine/install/centos/" "support matrix"
Assert-Contains $supportMatrix "https://docs.rockylinux.org/release_notes/10_0/" "support matrix"
Assert-Contains $supportMatrix "https://greenbone.github.io/docs/latest/22.4/container/index.html" "support matrix"
Assert-Contains $rockyRunbook "Rocky Linux 9.x or 10.x" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "x86_64 or aarch64" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Rocky's x86-64-v3 baseline" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "x86-64-v2 hardware is not a Rocky Linux 10 support target" "Rocky standalone runbook"
Assert-Contains $rockyRunbook '`ansible-core` 2.19.0 or newer' "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'controller `ansible-core` compatibility' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_install_mode: docker" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_docker_use_official_repo: true" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "python3 -m pip install --upgrade ansible-core" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Docker's RPM GPG key" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ansible-playbook -i inventories/rocky-standalone/hosts.local.yml site.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "playbooks/preflight-rocky-standalone.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "playbooks/bootstrap-rocky-standalone.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "before fact gathering" "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'Ansible `raw` commands' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "make rocky-preflight ROCKY_INVENTORY=inventories/rocky-standalone/hosts.local.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "make rocky-standalone ROCKY_INVENTORY=inventories/rocky-standalone/hosts.local.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "minimum CPU/RAM/disk" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "RPM package metadata" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "target Rocky major version and architecture" "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'supported `dnf` or `dnf5` package manager' "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'reports `ansible_pkg_mgr=dnf5`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_rocky_preflight_disk_check_path" "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'parent filesystem of `greenbone_work_dir`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "playbooks/validate-rocky-standalone.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "evidence includes" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "one valid Rocky 9 report and one valid Rocky 10 report" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "make rocky-validate ROCKY_INVENTORY=inventories/rocky-standalone/hosts.local.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Rocky's official BaseOS/AppStream" "Rocky standalone runbook"
Assert-Contains $rockyRunbook '`python3-dnf`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook '`python3-libdnf`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "python3 scripts/dev/Test-RockyDockerRepoMetadata.py" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Rocky smoke-test container images" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "quay.io/rockylinux/rockylinux:9" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "quay.io/rockylinux/rockylinux:10" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "python3 scripts/dev/Test-GreenboneContainerPlatforms.py" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "bash scripts/dev/Test-RockyDockerRepo.sh" "Rocky standalone runbook"
Assert-Contains $rockyRunbook ".\scripts\dev\Test-RockyDockerRepo.ps1" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY_DOCKER_REPO_SMOKE_TLS_VERIFY=false" "Rocky standalone runbook"
Assert-Contains $supportMatrix "ROCKY_DOCKER_REPO_SMOKE_TLS_VERIFY=false" "support matrix"
Assert-Contains $rockyDockerRepoSmoke "ROCKY_DOCKER_REPO_SMOKE_TLS_VERIFY" "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmokePs "ROCKY_DOCKER_REPO_SMOKE_TLS_VERIFY" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyRunbook "sudo docker compose -f /opt/greenbone-community/compose.yaml ps" "Rocky standalone runbook"
Assert-Contains $rockyRunbook ".secrets/rocky-standalone-evidence/<inventory-hostname>.json" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Test-RockyAcceptanceEvidence.py --max-age-hours 24 --summary-json" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "once on Rocky 9" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "and once on Rocky 10" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "GitHub Acceptance Workflow" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Local Acceptance Runner" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "bash scripts/dev/Run-RockyStandaloneAcceptance.sh" "Rocky standalone runbook"
Assert-Contains $rockyRunbook ".\scripts\dev\Run-RockyStandaloneAcceptance.ps1 -Distro Ubuntu" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY_SSH_PRIVATE_KEY_FILE" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY_ACCEPTANCE_WSL_DISTRO" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "path-translates" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY_ACCEPTANCE_SKIP_GALAXY=1" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY9_HOST" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY10_HOST" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY_BECOME_PASSWORD" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "python3 scripts/dev/Test-RockyAcceptanceReadiness.py" "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'requires the GitHub CLI `gh`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "required repository secret names" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "does not have passwordless sudo" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "verifies SSH" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "sudo access with an" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "does not require target" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Python yet" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "rejects hosts where" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "/opt/greenbone-community" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "known Greenbone" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "validated_at" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "last 24 hours" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "GitHub workflow" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "run ID and attempt values" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "rocky-standalone-evidence" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "rocky-standalone-diagnostics" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "recent" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Compose log diagnostics" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Docker info, SELinux" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "does not include" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "generated admin password" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "Self-hosted runners must be current enough for Node.js 24" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "v2.327.1 or later" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "required Docker RPM packages" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "validation timestamp" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "OS family, kernel, package manager" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "conditional DNF5" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "backend runtime status" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "controller" "Rocky standalone runbook"
Assert-Contains $rockyRunbook '`ansible-core`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "CPU" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "memory" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "free-disk facts" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "install mode" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "official Docker repo setting" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "localhost web bind" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "127.0.0.1:443" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "127.0.0.1:443:443" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "127.0.0.1:9392:9392" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "both endpoints respond locally" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY9_HOST" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY10_HOST" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "different" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ssh-keyscan -T 10" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "StrictHostKeyChecking=yes" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "required core compose" "Rocky standalone runbook"
Assert-Contains $rockyRunbook '`openvas`, `openvasd`, and `ospd-openvas`' "Rocky standalone runbook"
Assert-Contains $rockyRunbook "compose service listing" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "service readiness gate" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_rocky_validate_service_retries" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_rocky_validate_service_delay" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "password file exists, is non-empty" "Rocky standalone runbook"
Assert-Contains $rockyRunbook 'mode `0600`' "Rocky standalone runbook"
Assert-Contains $readme "Rocky Linux 9/10 (Docker standalone)" "README"
Assert-Contains $readme 'Rocky Linux 9/10 standalone installs must set `greenbone_install_mode: docker` explicitly' "README"
Assert-Contains $readme "x86_64 and aarch64" "README"
Assert-Contains $readme "Rocky's x86-64-v3 baseline" "README"
Assert-Contains $readme "greenbone_docker_use_official_repo: true" "README"
Assert-Contains $readmeEn "x86_64" "English README"
Assert-Contains $readmeEn "aarch64" "English README"
Assert-Contains $readmeEn 'Rocky Linux 9/10 standalone' "English README"
Assert-Contains $readmeEn "greenbone_docker_use_official_repo: true" "English README"
Assert-Contains $variablesDoc "greenbone_rocky_docker_supported_architectures" "variables documentation"
Assert-Contains $variablesDoc "Rocky Linux 9/10 standalone installs must set" "variables documentation"
Assert-Contains $variablesDoc "Rocky Linux 10 x86_64 follows Rocky's x86-64-v3 baseline" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky10_min_ansible_core_version" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky10_x86_64_v3_required_cpu_flag_groups" "variables documentation"
Assert-Contains $variablesDoc '`pni`/`sse3`' "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky_preflight_min_cpu_cores" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky_preflight_min_memory_mb" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky_preflight_min_disk_mb" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky_preflight_disk_check_path" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky_validate_service_retries" "variables documentation"
Assert-Contains $variablesDoc "greenbone_rocky_validate_service_delay" "variables documentation"
Assert-Contains $variablesDoc 'Parent of `greenbone_work_dir`' "variables documentation"
Assert-Contains $variablesDoc "greenbone_controller_secret_dir" "variables documentation"
Assert-Contains $variablesDoc 'Empty generates `.secrets/greenbone_admin_password`' "variables documentation"
Assert-Contains $variablesDoc "For Rocky Linux 9/10 standalone installs on x86_64 or aarch64" "variables documentation"
Assert-Contains $variablesDoc "greenbone_docker_use_official_repo: true" "variables documentation"
Assert-Contains $troubleshootingDoc "The target architecture is x86_64 or aarch64." "troubleshooting documentation"
Assert-Contains $troubleshootingDoc "greenbone_docker_use_official_repo" "troubleshooting documentation"
Assert-Contains $readmeAr "Rocky Linux 9/10" "Arabic README"
Assert-Contains $readmeEs "Rocky Linux 9/10" "Spanish README"
Assert-Contains $readmeHi "Rocky Linux 9/10" "Hindi README"
Assert-Contains $readmeZh "Rocky Linux 9/10" "Chinese README"
Assert-Contains $yamllint "  .venv/" "yamllint config"
Assert-Contains $yamllint "braces:" "yamllint config"
Assert-Contains $yamllint "max-spaces-inside: 1" "yamllint config"
Assert-Contains $yamllint "octal-values:" "yamllint config"
Assert-Contains $yamllint "forbid-implicit-octal: true" "yamllint config"
Assert-Contains $yamllint "forbid-explicit-octal: true" "yamllint config"
Assert-Contains $workflow "Test-SupportMatrix.ps1" "GitHub Actions workflow"
Assert-Contains $workflow "Test-RockyStandaloneSupport.ps1" "GitHub Actions workflow"
Assert-Contains $workflow "Run Rocky RPM repository metadata validation" "GitHub Actions workflow"
Assert-Contains $workflow "Test-GreenboneContainerPlatforms.py" "GitHub Actions workflow"
Assert-Contains $workflow "Test-RockyAcceptanceEvidence.py --self-test" "GitHub Actions workflow"
Assert-Contains $workflow "Render-RockyAcceptanceInventory.py --self-test" "GitHub Actions workflow"
Assert-Contains $workflow "bash -n scripts/dev/Run-RockyStandaloneAcceptance.sh" "GitHub Actions workflow"
Assert-Contains $workflow "Run-RockyStandaloneAcceptance.sh --self-test" "GitHub Actions workflow"
Assert-Contains $workflow "Test-RockyAcceptanceWorkflowShell.py" "GitHub Actions workflow"
Assert-Contains $workflow "Test-RockyAcceptanceReadiness.py --self-test" "GitHub Actions workflow"
Assert-Contains $workflow "actions/checkout@v7" "GitHub Actions workflow"
Assert-Contains $workflow "actions/setup-python@v6" "GitHub Actions workflow"
Assert-Contains $workflow "permissions:" "GitHub Actions workflow"
Assert-Contains $workflow "contents: read" "GitHub Actions workflow"
Assert-Contains $makefile "playbooks/bootstrap-rocky-standalone.yml --syntax-check" "Makefile"
Assert-Contains $workflow "playbooks/bootstrap-rocky-standalone.yml --syntax-check" "GitHub Actions workflow"
Assert-Contains $workflow "playbooks/preflight-rocky-standalone.yml --syntax-check" "GitHub Actions workflow"
Assert-Contains $workflow "playbooks/collect-rocky-standalone-diagnostics.yml --syntax-check" "GitHub Actions workflow"
Assert-Contains $acceptanceWorkflow "workflow_dispatch:" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "runner_label:" "Rocky acceptance workflow"
Assert-NotContains $acceptanceWorkflow "default: ubuntu-latest" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("runs-on: " + [char]36 + "{{ inputs.runner_label }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "actions/checkout@v7" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Clear previous Rocky local artifacts" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "rm -rf .secrets/rocky-standalone-evidence" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "rm -rf .secrets/rocky-standalone-diagnostics" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "actions/setup-python@v6" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "permissions:" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "contents: read" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "concurrency:" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "group: rocky-standalone-acceptance" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("ROCKY9_HOST: " + [char]36 + "{{ secrets.ROCKY9_HOST }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("ROCKY10_HOST: " + [char]36 + "{{ secrets.ROCKY10_HOST }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("ROCKY_BECOME_PASSWORD: " + [char]36 + "{{ secrets.ROCKY_BECOME_PASSWORD }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow '::add-mask::${ROCKY_BECOME_PASSWORD}' "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ROCKY_SSH_PORT must be an integer between 1 and 65535" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ROCKY9_HOST and ROCKY10_HOST must be different hosts" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ssh-keyscan -T 10" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Failed to collect SSH host key" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "SSH known_hosts is empty" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "SSH known_hosts does not contain valid host keys" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ssh-keygen -l -f ~/.ssh/known_hosts" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Render acceptance inventory" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Render-RockyAcceptanceInventory.py --output" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "--graph" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Verify Rocky SSH and sudo access" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ansible.builtin.raw" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "id -u && test -r /etc/os-release" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Verify Rocky acceptance hosts are clean" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Rocky acceptance hosts must be clean" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "/opt/greenbone-community" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "docker_name_format" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow 'printf "{%s}" "{.Names}"' "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "com.docker.compose.project=greenbone-community" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "greenbone-community[-_]" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "docker ps -a --format" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "openvasd" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Run Rocky standalone preflight" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "playbooks/preflight-rocky-standalone.yml" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Test-RockyAcceptanceEvidence.py" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "--max-age-hours 24" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow '--run-id "${GITHUB_RUN_ID}"' "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow '--run-attempt "${GITHUB_RUN_ATTEMPT}"' "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Collect Rocky diagnostics on failure" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "continue-on-error: true" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "playbooks/collect-rocky-standalone-diagnostics.yml" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "rocky-standalone-diagnostics" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "actions/upload-artifact@v7" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow 'if: always()' "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "if-no-files-found: warn" "Rocky acceptance workflow"
Assert-Contains $rockyDockerRepoMetadata 'RPM_ARCHITECTURES = ("x86_64", "aarch64")' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "ROCKY_PREREQUISITE_PACKAGES" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "ROCKY_SMOKE_IMAGES" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata '"quay.io/rockylinux/rockylinux:9"' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata '"quay.io/rockylinux/rockylinux:10"' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "REQUIRED_CONTAINER_PLATFORMS" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata '"python3-dnf"' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata '"python3-libdnf"' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata 'ROCKY_REPOSITORIES = ("BaseOS", "AppStream")' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "validate_rocky_prerequisites" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "official repos publish required prerequisites" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata 'GPG_KEY_URL = "https://download.docker.com/linux/centos/gpg"' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata 'validate_gpg_key()' "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "registry_bearer_token" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "manifest_platforms" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoMetadata "validate_smoke_image" "Rocky Docker repo metadata script"
Assert-Contains $rockyDockerRepoSmoke "curl_package=curl" "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmoke "quay.io/rockylinux/rockylinux:9" "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmoke "quay.io/rockylinux/rockylinux:10" "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmoke "rpm -q curl-minimal" "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmoke "curl_options+=(-k)" "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmoke 'dnf \"\${dnf_options[@]}\" -y install ca-certificates \"\${curl_package}\" dnf-plugins-core python3' "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmoke "Docker must be running for Rocky Docker repository smoke validation." "Rocky Docker repository smoke script"
Assert-Contains $rockyDockerRepoSmokePs "Invoke-NativeChecked" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs "Docker readiness check" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs "quay.io/rockylinux/rockylinux:9" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs "quay.io/rockylinux/rockylinux:10" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs "rpm -q curl-minimal" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs "curl_options+=(-k)" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs 'dnf "`${dnf_options[@]}" -y install ca-certificates "`${curl_package}" dnf-plugins-core python3' "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyDockerRepoSmokePs "docker compose -f `$composeFile config" "Rocky Docker repository PowerShell smoke script"
Assert-Contains $rockyAcceptanceInventoryRenderer "ROCKY_SSH_PORT must be an integer between 1 and 65535" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "ROCKY9_HOST and ROCKY10_HOST must be different hosts" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "ansible_ssh_private_key_file" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "ansible_become_password" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "ansible_ssh_common_args" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "rocky9-standalone" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "greenbone_expected_rocky_major_version: 9" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "rocky10-standalone" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "greenbone_expected_rocky_major_version: 10" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "greenbone_docker_use_official_repo" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "GITHUB_RUN_ID" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "greenbone_acceptance_run_id" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "GITHUB_RUN_ATTEMPT" "Rocky acceptance inventory renderer"
Assert-Contains $rockyAcceptanceInventoryRenderer "greenbone_acceptance_run_attempt" "Rocky acceptance inventory renderer"
Assert-Contains $rockyLocalAcceptanceRunner "ROCKY_SSH_PRIVATE_KEY_FILE" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "--self-test" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "Self-test did not reject a missing required environment variable" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "ROCKY_SSH_PRIVATE_KEY" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "ROCKY_SSH_KNOWN_HOSTS_FILE" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "ssh-keyscan -T 10" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "ssh-keygen -l -f" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "ansible-galaxy collection install -r requirements.yml" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "Render-RockyAcceptanceInventory.py" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "id -u && test -r /etc/os-release" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "Rocky acceptance hosts must be clean" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "/opt/greenbone-community" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "com.docker.compose.project=greenbone-community" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "playbooks/preflight-rocky-standalone.yml" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner 'ansible-playbook -i "${acceptance_inventory}" site.yml' "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "playbooks/validate-rocky-standalone.yml" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "playbooks/collect-rocky-standalone-diagnostics.yml" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "Test-RockyAcceptanceEvidence.py" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "--max-age-hours" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "--run-id" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunner "--run-attempt" "Rocky local acceptance runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "ROCKY_ACCEPTANCE_WSL_DISTRO" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "wsl.exe" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "wslpath -a" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "ROCKY_SSH_PRIVATE_KEY_FILE" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "ROCKY_SSH_KNOWN_HOSTS_FILE" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs '${_}/p' "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "WSLENV" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "Run-RockyStandaloneAcceptance.sh" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyLocalAcceptanceRunnerPs "--self-test" "Rocky local acceptance PowerShell runner"
Assert-Contains $rockyAcceptanceWorkflowShell "Verify Rocky acceptance hosts are clean" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "extract_single_quoted_raw_argument" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "assert_clean_host_raw_script" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "must not contain single quotes" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "shell_syntax_checks" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell 'syntax_check("sh"' "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell 'syntax_check("bash"' "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "{{.Names}}" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "com.docker.compose.project=greenbone-community" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceWorkflowShell "greenbone-community[-_]" "Rocky acceptance workflow shell script"
Assert-Contains $rockyAcceptanceReadiness "REQUIRED_SECRETS" "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '"ROCKY9_HOST"' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '"ROCKY10_HOST"' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '"ROCKY_SSH_USER"' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '"ROCKY_SSH_PRIVATE_KEY"' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness 'GitHub CLI `gh` is required' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '["gh", "auth", "status"]' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '["gh", "workflow", "list", "--all", "--json", "name,path,state"]' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '["gh", "secret", "list", "--json", "name"]' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness '["gh", "variable", "list", "--json", "name,value"]' "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness "ROCKY_SSH_PORT repository variable must be between 1 and 65535" "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceReadiness "--self-test" "Rocky acceptance readiness script"
Assert-Contains $rockyAcceptanceEvidence "DEFAULT_EXPECTED_HOSTS" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "def evidence_summary" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "--summary-json" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"status": "valid"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "rocky9-standalone" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "rocky10-standalone" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "validated_at" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "DEFAULT_MAX_ACCEPTANCE_EVIDENCE_AGE_HOURS" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "validated_at must be an ISO 8601 timestamp" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "acceptance evidence is older than" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "--max-age-hours" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "--run-id" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "--run-attempt" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "acceptance_run_id does not match this workflow run" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "acceptance_run_attempt does not match this workflow attempt" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "install_mode" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "official_docker_repo_enabled" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"openvas"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"openvasd"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"ospd-openvas"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "Unexpected evidence report files" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "stale-rocky.json" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "_as_string_list" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "compose_ps evidence must not be empty" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "compose_ps_collected_after_service_wait" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "compose_ps must be collected after" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "MINIMUM_SERVICE_WAIT_SECONDS = 900" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "service_wait_timeout_seconds does not match" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "service wait timeout must be at least" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "missing running services: openvas" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "MINIMUM_CPU_CORES = 4" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "MINIMUM_MEMORY_MB = 8192" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "MINIMUM_DISK_MB = 61440" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "EXPECTED_DOCKER_RPM_REPO_FILE" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "SUPPORTED_PACKAGE_MANAGERS" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "package_manager must be one of" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "DNF5 backend runtime check must be recorded" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "python3-libdnf5 must be installed" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"package_manager": "dnf"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"package_manager"] = "dnf5"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "MINIMUM_ANSIBLE_CORE_VERSION_FOR_ROCKY10" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "MINIMUM_ANSIBLE_CORE_VERSION_FOR_ROCKY10_TEXT" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "ROCKY10_X86_64_V3_REQUIRED_CPU_FLAG_GROUPS" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence '"abm", "lzcnt"' "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "Rocky 10 x86_64 CPU flag check must be recorded" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "missing Rocky 10 x86-64-v3 CPU feature groups" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "ansible_core_version must be at least" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "minimum_ansible_core_version_for_rocky10 must be" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "EXPECTED_WEB_BIND_ADDRESS" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "EXPECTED_WEB_HTTPS_PORT" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "EXPECTED_WEB_GSAD_PORT" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "minimum_cpu_cores" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "disk_mb_available" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "admin_password_file_size" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "admin_password_file_mode" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "REQUIRED_DOCKER_RPM_PACKAGES" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "docker_rpm_repo_uses_docker_centos_repo" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "docker_rpm_repo_gpgcheck_enabled" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "docker_rpm_repo_gpgkey_url_present" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "Docker RPM repository file must be" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "Docker RPM repository must have gpgcheck=1" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "Docker RPM repository must use Docker's CentOS RPM GPG key" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "docker_version does not look like Docker Engine output" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "compose_file must point to a compose.yaml file" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "web_bind_address must be 127.0.0.1" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "web_https_port must be 443" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "web_gsad_port must be 9392" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "expected HTTPS web mapping" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "expected GSAD web mapping" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "web_gsad_probe_status" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "unexpected GSAD web probe status" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "--self-test" "Rocky acceptance evidence script"
Assert-Contains $greenboneContainerPlatforms "REQUIRED_PLATFORMS" "Greenbone container platform script"
Assert-Contains $greenboneContainerPlatforms "REQUIRED_COMPOSE_SERVICES" "Greenbone container platform script"
Assert-Contains $greenboneContainerPlatforms "REQUIRED_NGINX_PORTS" "Greenbone container platform script"
Assert-Contains $greenboneContainerPlatforms "assert_compose_topology(compose)" "Greenbone container platform script"
Assert-Contains $rockyDiagnosticsPlaybook "Collect Rocky Linux standalone Docker diagnostics" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "greenbone_diag_dir" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "rocky-standalone-diagnostics" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "compose_logs_stdout" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "docker_service_stdout" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "docker_info_stdout" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "selinux_stdout" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "firewalld_stdout" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "docker_rpm_repo_gpgcheck_enabled" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "(greenbone_diag_docker_repo_gpgcheck_marker | default('')) in" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "(greenbone_diag_docker_repo_gpgkey_marker | default('')) in" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "(greenbone_diag_docker_rpm_gpg_key_id | default('')) in" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "greenbone_diag_python3_libdnf5" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "'python3_libdnf5_installed': greenbone_diag_python3_libdnf5.rc == 0" "Rocky diagnostics playbook"
Assert-Contains $rockyDiagnosticsPlaybook "'ansible_core_version': ansible_version.full" "Rocky diagnostics playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_min_cpu_cores" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_min_memory_mb" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_min_disk_mb" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Assert target has minimum Greenbone container resources" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_docker_rpm_repo_gpgcheck_marker" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "(greenbone_validate_docker_rpm_repo_marker | default('')) in" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "(greenbone_validate_docker_rpm_gpg_key_id | default('')) in" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "(greenbone_validate_compose_web_https_mapping | default('')) in" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_docker_rpm_repo_gpgkey_marker" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Docker's CentOS RPM GPG key configured" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_rocky10_min_ansible_core_version" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_rocky10_x86_64_v3_required_cpu_flag_groups" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_validate_rocky10_x86_64_v3_missing_cpu_flags" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Assert Rocky Linux 10 x86_64 target meets x86-64-v3 CPU baseline" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'cpu_flags': greenbone_validate_cpu_flags" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'rocky10_x86_64_v3_cpu_flags_checked':" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Assert controller ansible-core supports Rocky Linux 10" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_rocky_validate_service_retries | default(60)" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "greenbone_rocky_validate_service_delay | default(15)" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'acceptance_run_id': greenbone_acceptance_run_id | default('')" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'acceptance_run_attempt': greenbone_acceptance_run_attempt | default('')" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Assert required Docker RPM packages are installed" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Missing required Docker RPM packages" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'package_manager': ansible_pkg_mgr | default('unknown')" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Assert Rocky Linux reports a supported package manager" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "ansible_pkg_mgr | default('unknown') in ['dnf', 'dnf5']" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Check python3-libdnf5 package for DNF5 package-manager backend" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "Assert DNF5 package-manager backend runtime is installed" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'dnf5_backend_checked': ansible_pkg_mgr | default('unknown') == 'dnf5'" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'python3_libdnf5_installed':" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'ansible_core_version': ansible_version.full" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'cpu_cores': greenbone_validate_cpu_cores | int" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'disk_mb_available': greenbone_validate_disk_mb_available | int" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'service_wait_retries': greenbone_validate_service_retries | int" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'service_wait_delay_seconds': greenbone_validate_service_delay | int" "Rocky validation playbook"
Assert-Contains $rockyValidationPlaybook "'service_wait_timeout_seconds':" "Rocky validation playbook"
Assert-Contains $rockyPreflightPlaybook "Preflight Rocky Linux standalone Docker targets" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_rocky_preflight_min_cpu_cores" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_rocky_preflight_min_memory_mb" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_rocky_preflight_min_disk_mb" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_rocky10_min_ansible_core_version" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_rocky10_x86_64_v3_required_cpu_flag_groups" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_rocky10_x86_64_v3_missing_cpu_flags" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Assert Rocky Linux 10 x86_64 target meets x86-64-v3 CPU baseline" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "ansible_processor_flags | default" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "map('lower') | list" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_rocky_preflight_disk_check_path" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_default_docker_rpm_packages" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_docker_rpm_packages" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_default_disk_check_path" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "| dirname" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_min_cpu_cores | int" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_min_memory_mb | int" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_preflight_min_disk_mb | int" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Assert target has minimum Greenbone container resources" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_expected_rocky_major_version is not defined or" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Assert controller ansible-core supports Rocky Linux 10" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Assert Rocky Linux reports a supported package manager" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "ansible_pkg_mgr | default('unknown') in ['dnf', 'dnf5']" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_install_mode == 'docker'" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "greenbone_docker_use_official_repo | default(true) | bool" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "https://download.docker.com/linux/centos/docker-ce.repo" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "https://download.docker.com/linux/centos/gpg" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Record target Docker RPM metadata URL" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "stable/Packages/" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Check Docker RPM metadata for target release and architecture" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "return_content: true" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "Assert Docker RPM metadata publishes required packages" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "regex_escape" "Rocky preflight playbook"
Assert-Contains $rockyPreflightPlaybook "https://registry.community.greenbone.net/v2/" "Rocky preflight playbook"

Write-Host "Support matrix validation passed."
