$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")

function Read-RepoFile {
    param([string] $RelativePath)
    Get-Content -Raw -Path (Join-Path $RepoRoot $RelativePath)
}

function Assert-Contains {
    param(
        [string] $Text,
        [string] $Needle,
        [string] $Context
    )

    if (-not $Text.Contains($Needle)) {
        throw "Missing expected content in ${Context}: ${Needle}"
    }
}

$commonDefaults = Read-RepoFile "roles/greenbone_common/defaults/main.yml"
$commonTasks = Read-RepoFile "roles/greenbone_common/tasks/main.yml"
$dockerDefaults = Read-RepoFile "roles/greenbone_docker/defaults/main.yml"
$redhatTasks = Read-RepoFile "roles/greenbone_docker/tasks/redhat.yml"
$masterDockerTasks = Read-RepoFile "roles/greenbone_master/tasks/docker.yml"
$rockyInventory = Read-RepoFile "inventories/rocky-standalone/hosts.yml"
$rockyDockerRepoMetadata = Read-RepoFile "scripts/dev/Test-RockyDockerRepoMetadata.py"
$rockyAcceptanceEvidence = Read-RepoFile "scripts/dev/Test-RockyAcceptanceEvidence.py"
$greenboneContainerPlatforms = Read-RepoFile "scripts/dev/Test-GreenboneContainerPlatforms.py"
$supportMatrix = Read-RepoFile "docs/support-matrix.md"
$rockyRunbook = Read-RepoFile "docs/rocky-standalone.md"
$variablesDoc = Read-RepoFile "docs/variables.md"
$troubleshootingDoc = Read-RepoFile "docs/troubleshooting.md"
$readme = Read-RepoFile "README.md"
$readmeEn = Read-RepoFile "docs/README.en.md"
$readmeAr = Read-RepoFile "docs/README.ar.md"
$readmeEs = Read-RepoFile "docs/README.es.md"
$readmeHi = Read-RepoFile "docs/README.hi.md"
$readmeZh = Read-RepoFile "docs/README.zh.md"
$yamllint = Read-RepoFile ".yamllint.yml"
$workflow = Read-RepoFile ".github/workflows/ansible-lint.yml"
$acceptanceWorkflow = Read-RepoFile ".github/workflows/rocky-standalone-acceptance.yml"

Assert-Contains $commonDefaults "greenbone_rocky_docker_supported_major_versions:" "common defaults"
Assert-Contains $commonDefaults "  - 9" "common defaults"
Assert-Contains $commonDefaults "  - 10" "common defaults"
Assert-Contains $commonDefaults "greenbone_rocky_docker_supported_architectures:" "common defaults"
Assert-Contains $commonDefaults "  - x86_64" "common defaults"
Assert-Contains $commonDefaults "  - aarch64" "common defaults"
Assert-Contains $commonTasks "Assert Rocky Linux Docker standalone support" "common tasks"
Assert-Contains $commonTasks "greenbone_effective_install_mode == 'docker'" "common tasks"
Assert-Contains $commonTasks "ansible_distribution_major_version | int in greenbone_rocky_docker_supported_major_versions" "common tasks"
Assert-Contains $commonTasks "ansible_architecture in greenbone_rocky_docker_supported_architectures" "common tasks"
Assert-Contains $commonTasks "greenbone_docker_use_official_repo | default(true) | bool" "common tasks"
Assert-Contains $dockerDefaults "  - podman" "docker defaults"
Assert-Contains $redhatTasks "greenbone_docker_rpm_repo_family" "redhat docker tasks"
Assert-Contains $redhatTasks "else 'centos'" "redhat docker tasks"
Assert-Contains $redhatTasks "https://download.docker.com/linux/{{ greenbone_docker_rpm_repo_family }}/docker-ce.repo" "redhat docker tasks"
Assert-Contains $masterDockerTasks "Assert Greenbone Docker compose web port mappings are patched" "master Docker tasks"
Assert-Contains $masterDockerTasks "Validate Greenbone Docker compose configuration" "master Docker tasks"
Assert-Contains $rockyInventory "greenbone_install_mode: docker" "rocky standalone inventory"
Assert-Contains $rockyInventory "greenbone_docker_use_official_repo: true" "rocky standalone inventory"
Assert-Contains $rockyInventory "ansible_user: rocky" "rocky standalone inventory"
Assert-Contains $supportMatrix "| Rocky Linux | 9.x | x86_64, aarch64 | Docker standalone master | Docker CentOS RPM repo | Supported by this project |" "support matrix"
Assert-Contains $supportMatrix "| Rocky Linux | 10.x | x86_64, aarch64 | Docker standalone master | Docker CentOS RPM repo | Supported by this project |" "support matrix"
Assert-Contains $supportMatrix "greenbone_docker_use_official_repo: true" "support matrix"
Assert-Contains $supportMatrix "The CI smoke check does not start the full Greenbone stack" "support matrix"
Assert-Contains $supportMatrix "validates Docker's CentOS 9 and 10 RPM package publication for x86_64" "support matrix"
Assert-Contains $supportMatrix "publish both linux/amd64 and linux/arm64 manifests" "support matrix"
Assert-Contains $supportMatrix "real Rocky 9 and Rocky 10 hosts" "support matrix"
Assert-Contains $supportMatrix ".github/workflows/rocky-standalone-acceptance.yml" "support matrix"
Assert-Contains $supportMatrix "waits for required core compose services" "support matrix"
Assert-Contains $supportMatrix "checks the local HTTPS endpoint" "support matrix"
Assert-Contains $supportMatrix "generated admin password file exists, is non-empty, and is mode" "support matrix"
Assert-Contains $supportMatrix "one complete Rocky 9 report" "support matrix"
Assert-Contains $supportMatrix "complete Rocky 10 report" "support matrix"
Assert-Contains $rockyRunbook "Rocky Linux 9.x or 10.x" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "x86_64 or aarch64" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_install_mode: docker" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "greenbone_docker_use_official_repo: true" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ansible-playbook -i inventories/rocky-standalone/hosts.local.yml site.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "make rocky-standalone ROCKY_INVENTORY=inventories/rocky-standalone/hosts.local.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "playbooks/validate-rocky-standalone.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "one valid Rocky 9 report and one valid Rocky 10 report" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "make rocky-validate ROCKY_INVENTORY=inventories/rocky-standalone/hosts.local.yml" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "python3 scripts/dev/Test-RockyDockerRepoMetadata.py" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "python3 scripts/dev/Test-GreenboneContainerPlatforms.py" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "sudo docker compose -f /opt/greenbone-community/compose.yaml ps" "Rocky standalone runbook"
Assert-Contains $rockyRunbook ".secrets/rocky-standalone-evidence/<inventory-hostname>.json" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "once on Rocky 9" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "and once on Rocky 10" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "GitHub Acceptance Workflow" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY9_HOST" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "ROCKY10_HOST" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "rocky-standalone-evidence" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "required core compose" "Rocky standalone runbook"
Assert-Contains $rockyRunbook "controller-side password file exists, is non-empty, and is mode" "Rocky standalone runbook"
Assert-Contains $readme "Rocky Linux 9/10 (Docker standalone)" "README"
Assert-Contains $readme "x86_64 and aarch64" "README"
Assert-Contains $readme "greenbone_docker_use_official_repo: true" "README"
Assert-Contains $readmeEn "x86_64" "English README"
Assert-Contains $readmeEn "aarch64" "English README"
Assert-Contains $readmeEn "greenbone_docker_use_official_repo: true" "English README"
Assert-Contains $variablesDoc "greenbone_rocky_docker_supported_architectures" "variables documentation"
Assert-Contains $variablesDoc 'Empty generates `.secrets/greenbone_admin_password`' "variables documentation"
Assert-Contains $variablesDoc "For Rocky Linux 9/10 standalone installs on x86_64 or aarch64" "variables documentation"
Assert-Contains $variablesDoc "greenbone_docker_use_official_repo: true" "variables documentation"
Assert-Contains $troubleshootingDoc "The target architecture is x86_64 or aarch64." "troubleshooting documentation"
Assert-Contains $troubleshootingDoc "greenbone_docker_use_official_repo" "troubleshooting documentation"
Assert-Contains $readmeAr "Rocky Linux 9/10" "Arabic README"
Assert-Contains $readmeEs "Rocky Linux 9/10" "Spanish README"
Assert-Contains $readmeHi "Rocky Linux 9/10" "Hindi README"
Assert-Contains $readmeZh "Rocky Linux 9/10" "Chinese README"
Assert-Contains $yamllint "  .venv/" "yamllint config"
Assert-Contains $workflow "Test-SupportMatrix.ps1" "GitHub Actions workflow"
Assert-Contains $workflow "Test-RockyStandaloneSupport.ps1" "GitHub Actions workflow"
Assert-Contains $workflow "Test-GreenboneContainerPlatforms.py" "GitHub Actions workflow"
Assert-Contains $workflow "Test-RockyAcceptanceEvidence.py --self-test" "GitHub Actions workflow"
Assert-Contains $workflow "actions/checkout@v7" "GitHub Actions workflow"
Assert-Contains $workflow "actions/setup-python@v6" "GitHub Actions workflow"
Assert-Contains $acceptanceWorkflow "workflow_dispatch:" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "runner_label:" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("runs-on: " + [char]36 + "{{ inputs.runner_label }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "actions/checkout@v7" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "actions/setup-python@v6" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("ROCKY9_HOST: " + [char]36 + "{{ secrets.ROCKY9_HOST }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow ("ROCKY10_HOST: " + [char]36 + "{{ secrets.ROCKY10_HOST }}") "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ROCKY_SSH_PORT must be an integer between 1 and 65535" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow 'ansible_ssh_private_key_file: "${HOME}/.ssh/id_ed25519"' "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "greenbone_docker_use_official_repo: true" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Verify Rocky SSH and sudo access" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "ansible.builtin.ping --become" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Clear previous Rocky acceptance evidence" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "rm -rf .secrets/rocky-standalone-evidence" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "Test-RockyAcceptanceEvidence.py" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "actions/upload-artifact@v7" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "if: always()" "Rocky acceptance workflow"
Assert-Contains $acceptanceWorkflow "if-no-files-found: warn" "Rocky acceptance workflow"
Assert-Contains $rockyDockerRepoMetadata 'RPM_ARCHITECTURES = ("x86_64", "aarch64")' "Rocky Docker repo metadata script"
Assert-Contains $rockyAcceptanceEvidence "DEFAULT_EXPECTED_HOSTS" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "rocky9-standalone" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "rocky10-standalone" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "Unexpected evidence report files" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "stale-rocky.json" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "_as_string_list" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "compose_ps evidence must not be empty" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "admin_password_file_size" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "admin_password_file_mode" "Rocky acceptance evidence script"
Assert-Contains $rockyAcceptanceEvidence "--self-test" "Rocky acceptance evidence script"
Assert-Contains $greenboneContainerPlatforms "REQUIRED_PLATFORMS" "Greenbone container platform script"

Write-Host "Support matrix validation passed."
