---
- name: Install Docker packages on Alpine
  community.general.apk:
    name: "{{ greenbone_docker_alpine_packages }}"
    state: present
    update_cache: true

- name: Enable Docker OpenRC service on Alpine
  ansible.builtin.command: rc-update add docker default
  register: greenbone_docker_alpine_rc_update
  changed_when: "'service docker added' in greenbone_docker_alpine_rc_update.stdout"
  failed_when: false
